export const GET_PRODUCT_DETAIL_ID = "GET_PRODUCT_DETAIL_ID"
export const ADD_PRODUCTDETAIL_TO_CART = "ADD_PRODUCTDETAIL_TO_CART"
export const INCREMENT_PRODUCT = "INCREMENT_PRODUCT"
export const DECREMENT_PRODUCT = "DECREMENT_PRODUCT"